/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as WaterRouteImport } from './routes/water'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as SymptomCheckerRouteImport } from './routes/symptom-checker'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefillRouteImport } from './routes/refill'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HealthRiskRouteImport } from './routes/health-risk'
import { Route as HealthCardRouteImport } from './routes/health-card'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ExerciseRouteImport } from './routes/exercise'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as CaregiversRouteImport } from './routes/caregivers'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterRoute = WaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomCheckerRoute = SymptomCheckerRouteImport.update({
  id: '/symptom-checker',
  path: '/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefillRoute = RefillRouteImport.update({
  id: '/refill',
  path: '/refill',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRiskRoute = HealthRiskRouteImport.update({
  id: '/health-risk',
  path: '/health-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthCardRoute = HealthCardRouteImport.update({
  id: '/health-card',
  path: '/health-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseRoute = ExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiversRoute = CaregiversRouteImport.update({
  id: '/caregivers',
  path: '/caregivers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/caregivers': typeof CaregiversRoute
  '/consultations': typeof ConsultationsRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/exercise': typeof ExerciseRoute
  '/family': typeof FamilyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health-card': typeof HealthCardRoute
  '/health-risk': typeof HealthRiskRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/mood': typeof MoodRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/pharmacy': typeof PharmacyRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/refill': typeof RefillRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/stock': typeof StockRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/vault': typeof VaultRoute
  '/voice': typeof VoiceRoute
  '/water': typeof WaterRoute
  '/wellness': typeof WellnessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/caregivers': typeof CaregiversRoute
  '/consultations': typeof ConsultationsRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/exercise': typeof ExerciseRoute
  '/family': typeof FamilyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health-card': typeof HealthCardRoute
  '/health-risk': typeof HealthRiskRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/mood': typeof MoodRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/pharmacy': typeof PharmacyRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/refill': typeof RefillRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/stock': typeof StockRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/vault': typeof VaultRoute
  '/voice': typeof VoiceRoute
  '/water': typeof WaterRoute
  '/wellness': typeof WellnessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/caregivers': typeof CaregiversRoute
  '/consultations': typeof ConsultationsRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/exercise': typeof ExerciseRoute
  '/family': typeof FamilyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health-card': typeof HealthCardRoute
  '/health-risk': typeof HealthRiskRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/mood': typeof MoodRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/pharmacy': typeof PharmacyRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/refill': typeof RefillRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/stock': typeof StockRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/vault': typeof VaultRoute
  '/voice': typeof VoiceRoute
  '/water': typeof WaterRoute
  '/wellness': typeof WellnessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/assistant'
    | '/calendar'
    | '/caregivers'
    | '/consultations'
    | '/dashboard'
    | '/doctors'
    | '/emergency'
    | '/exercise'
    | '/family'
    | '/forgot-password'
    | '/health-card'
    | '/health-risk'
    | '/history'
    | '/login'
    | '/medicines'
    | '/mood'
    | '/nearby'
    | '/notifications'
    | '/pharmacy'
    | '/prescriptions'
    | '/profile'
    | '/refill'
    | '/register'
    | '/reminders'
    | '/reset-password'
    | '/rewards'
    | '/schemes'
    | '/settings'
    | '/sleep'
    | '/stock'
    | '/symptom-checker'
    | '/vault'
    | '/voice'
    | '/water'
    | '/wellness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/assistant'
    | '/calendar'
    | '/caregivers'
    | '/consultations'
    | '/dashboard'
    | '/doctors'
    | '/emergency'
    | '/exercise'
    | '/family'
    | '/forgot-password'
    | '/health-card'
    | '/health-risk'
    | '/history'
    | '/login'
    | '/medicines'
    | '/mood'
    | '/nearby'
    | '/notifications'
    | '/pharmacy'
    | '/prescriptions'
    | '/profile'
    | '/refill'
    | '/register'
    | '/reminders'
    | '/reset-password'
    | '/rewards'
    | '/schemes'
    | '/settings'
    | '/sleep'
    | '/stock'
    | '/symptom-checker'
    | '/vault'
    | '/voice'
    | '/water'
    | '/wellness'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/appointments'
    | '/assistant'
    | '/calendar'
    | '/caregivers'
    | '/consultations'
    | '/dashboard'
    | '/doctors'
    | '/emergency'
    | '/exercise'
    | '/family'
    | '/forgot-password'
    | '/health-card'
    | '/health-risk'
    | '/history'
    | '/login'
    | '/medicines'
    | '/mood'
    | '/nearby'
    | '/notifications'
    | '/pharmacy'
    | '/prescriptions'
    | '/profile'
    | '/refill'
    | '/register'
    | '/reminders'
    | '/reset-password'
    | '/rewards'
    | '/schemes'
    | '/settings'
    | '/sleep'
    | '/stock'
    | '/symptom-checker'
    | '/vault'
    | '/voice'
    | '/water'
    | '/wellness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AssistantRoute: typeof AssistantRoute
  CalendarRoute: typeof CalendarRoute
  CaregiversRoute: typeof CaregiversRoute
  ConsultationsRoute: typeof ConsultationsRoute
  DashboardRoute: typeof DashboardRoute
  DoctorsRoute: typeof DoctorsRoute
  EmergencyRoute: typeof EmergencyRoute
  ExerciseRoute: typeof ExerciseRoute
  FamilyRoute: typeof FamilyRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthCardRoute: typeof HealthCardRoute
  HealthRiskRoute: typeof HealthRiskRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MedicinesRoute: typeof MedicinesRoute
  MoodRoute: typeof MoodRoute
  NearbyRoute: typeof NearbyRoute
  NotificationsRoute: typeof NotificationsRoute
  PharmacyRoute: typeof PharmacyRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  ProfileRoute: typeof ProfileRoute
  RefillRoute: typeof RefillRoute
  RegisterRoute: typeof RegisterRoute
  RemindersRoute: typeof RemindersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  SchemesRoute: typeof SchemesRoute
  SettingsRoute: typeof SettingsRoute
  SleepRoute: typeof SleepRoute
  StockRoute: typeof StockRoute
  SymptomCheckerRoute: typeof SymptomCheckerRoute
  VaultRoute: typeof VaultRoute
  VoiceRoute: typeof VoiceRoute
  WaterRoute: typeof WaterRoute
  WellnessRoute: typeof WellnessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water': {
      id: '/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof WaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom-checker': {
      id: '/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof SymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refill': {
      id: '/refill'
      path: '/refill'
      fullPath: '/refill'
      preLoaderRoute: typeof RefillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-risk': {
      id: '/health-risk'
      path: '/health-risk'
      fullPath: '/health-risk'
      preLoaderRoute: typeof HealthRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-card': {
      id: '/health-card'
      path: '/health-card'
      fullPath: '/health-card'
      preLoaderRoute: typeof HealthCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise': {
      id: '/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof ExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregivers': {
      id: '/caregivers'
      path: '/caregivers'
      fullPath: '/caregivers'
      preLoaderRoute: typeof CaregiversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppointmentsRoute: AppointmentsRoute,
  AssistantRoute: AssistantRoute,
  CalendarRoute: CalendarRoute,
  CaregiversRoute: CaregiversRoute,
  ConsultationsRoute: ConsultationsRoute,
  DashboardRoute: DashboardRoute,
  DoctorsRoute: DoctorsRoute,
  EmergencyRoute: EmergencyRoute,
  ExerciseRoute: ExerciseRoute,
  FamilyRoute: FamilyRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthCardRoute: HealthCardRoute,
  HealthRiskRoute: HealthRiskRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MedicinesRoute: MedicinesRoute,
  MoodRoute: MoodRoute,
  NearbyRoute: NearbyRoute,
  NotificationsRoute: NotificationsRoute,
  PharmacyRoute: PharmacyRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  ProfileRoute: ProfileRoute,
  RefillRoute: RefillRoute,
  RegisterRoute: RegisterRoute,
  RemindersRoute: RemindersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  SchemesRoute: SchemesRoute,
  SettingsRoute: SettingsRoute,
  SleepRoute: SleepRoute,
  StockRoute: StockRoute,
  SymptomCheckerRoute: SymptomCheckerRoute,
  VaultRoute: VaultRoute,
  VoiceRoute: VoiceRoute,
  WaterRoute: WaterRoute,
  WellnessRoute: WellnessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
